# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: maps_example/proto/example.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n maps_example/proto/example.proto\"\x19\n\x04User\x12\x11\n\tnick_name\x18\x01 \x01(\t\"c\n\x06Person\x12#\n\x06person\x18\x03 \x03(\x0b\x32\x13.Person.PersonEntry\x1a\x34\n\x0bPersonEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x14\n\x05value\x18\x02 \x01(\x0b\x32\x05.User:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'maps_example.proto.example_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PERSON_PERSONENTRY']._options = None
  _globals['_PERSON_PERSONENTRY']._serialized_options = b'8\001'
  _globals['_USER']._serialized_start=36
  _globals['_USER']._serialized_end=61
  _globals['_PERSON']._serialized_start=63
  _globals['_PERSON']._serialized_end=162
  _globals['_PERSON_PERSONENTRY']._serialized_start=110
  _globals['_PERSON_PERSONENTRY']._serialized_end=162
# @@protoc_insertion_point(module_scope)
