# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: todo.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntodo.proto\x12\x04todo\"O\n\x0bTodoElement\x12\n\n\x02Id\x18\x01 \x01(\t\x12\r\n\x05Title\x18\x02 \x01(\t\x12\x13\n\x0b\x44\x65scription\x18\x03 \x01(\t\x12\x10\n\x08\x46inished\x18\x04 \x01(\x08\"\x14\n\x06TodoId\x12\n\n\x02Id\x18\x01 \x01(\t\"\x18\n\x07Succeed\x12\r\n\x05value\x18\x01 \x01(\x08\"\x07\n\x05\x45mpty2\xa9\x02\n\x0bToDoService\x12/\n\nCreateTodo\x12\x11.todo.TodoElement\x1a\x0c.todo.TodoId\"\x00\x12,\n\x07GetTodo\x12\x0c.todo.TodoId\x1a\x11.todo.TodoElement\"\x00\x12\x31\n\x0bGetAllTodos\x12\x0b.todo.Empty\x1a\x11.todo.TodoElement\"\x00\x30\x01\x12+\n\nFinishTodo\x12\x0c.todo.TodoId\x1a\r.todo.Succeed\"\x00\x12.\n\x08\x45\x64itTodo\x12\x11.todo.TodoElement\x1a\r.todo.Succeed\"\x00\x12+\n\nRemoveTodo\x12\x0c.todo.TodoId\x1a\r.todo.Succeed\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'todo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TODOELEMENT']._serialized_start=20
  _globals['_TODOELEMENT']._serialized_end=99
  _globals['_TODOID']._serialized_start=101
  _globals['_TODOID']._serialized_end=121
  _globals['_SUCCEED']._serialized_start=123
  _globals['_SUCCEED']._serialized_end=147
  _globals['_EMPTY']._serialized_start=149
  _globals['_EMPTY']._serialized_end=156
  _globals['_TODOSERVICE']._serialized_start=159
  _globals['_TODOSERVICE']._serialized_end=456
# @@protoc_insertion_point(module_scope)
