# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from book_site_example.proto.protobuf import book_pb2 as protobuf_dot_book__pb2


class StoreStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAllBooks = channel.unary_stream(
                '/Store/GetAllBooks',
                request_serializer=protobuf_dot_book__pb2.Empty.SerializeToString,
                response_deserializer=protobuf_dot_book__pb2.Book.FromString,
                )
        self.GetBook = channel.unary_unary(
                '/Store/GetBook',
                request_serializer=protobuf_dot_book__pb2.BookTitle.SerializeToString,
                response_deserializer=protobuf_dot_book__pb2.Book.FromString,
                )
        self.AddBook = channel.unary_unary(
                '/Store/AddBook',
                request_serializer=protobuf_dot_book__pb2.Book.SerializeToString,
                response_deserializer=protobuf_dot_book__pb2.Book.FromString,
                )
        self.RemoveBook = channel.unary_unary(
                '/Store/RemoveBook',
                request_serializer=protobuf_dot_book__pb2.BookTitle.SerializeToString,
                response_deserializer=protobuf_dot_book__pb2.Status.FromString,
                )


class StoreServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAllBooks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAllBooks': grpc.unary_stream_rpc_method_handler(
                    servicer.GetAllBooks,
                    request_deserializer=protobuf_dot_book__pb2.Empty.FromString,
                    response_serializer=protobuf_dot_book__pb2.Book.SerializeToString,
            ),
            'GetBook': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBook,
                    request_deserializer=protobuf_dot_book__pb2.BookTitle.FromString,
                    response_serializer=protobuf_dot_book__pb2.Book.SerializeToString,
            ),
            'AddBook': grpc.unary_unary_rpc_method_handler(
                    servicer.AddBook,
                    request_deserializer=protobuf_dot_book__pb2.Book.FromString,
                    response_serializer=protobuf_dot_book__pb2.Book.SerializeToString,
            ),
            'RemoveBook': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveBook,
                    request_deserializer=protobuf_dot_book__pb2.BookTitle.FromString,
                    response_serializer=protobuf_dot_book__pb2.Status.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Store', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Store(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAllBooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Store/GetAllBooks',
            protobuf_dot_book__pb2.Empty.SerializeToString,
            protobuf_dot_book__pb2.Book.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Store/GetBook',
            protobuf_dot_book__pb2.BookTitle.SerializeToString,
            protobuf_dot_book__pb2.Book.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Store/AddBook',
            protobuf_dot_book__pb2.Book.SerializeToString,
            protobuf_dot_book__pb2.Book.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Store/RemoveBook',
            protobuf_dot_book__pb2.BookTitle.SerializeToString,
            protobuf_dot_book__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
