# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rexample.proto\"!\n\x05\x43\x61ndy\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x05\"C\n\x08\x43\x61ndyBox\x12\x19\n\tone_candy\x18\x01 \x01(\x0b\x32\x06.Candy\x12\x1c\n\x0cmany_candies\x18\x02 \x03(\x0b\x32\x06.Candyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CANDY']._serialized_start=17
  _globals['_CANDY']._serialized_end=50
  _globals['_CANDYBOX']._serialized_start=52
  _globals['_CANDYBOX']._serialized_end=119
# @@protoc_insertion_point(module_scope)
